export const UPDATE_ENTRIE_LIST_REQUEST ="UPDATE_ENTRIE_LIST_REQUEST"
export const UPDATE_ENTRIE_LIST_SUCCESS ="UPDATE_ENTRIE_LIST_SUCCESS"
export const UPDATE_ENTRIE_LIST_FAIL ="UPDATE_ENTRIE_LIST_FAIL"



export const CLEAR_ERRORS ="CLEAR_ERRORS"