export const UPDATE_NETWORK_REQUEST ="UPDATE_NETWORK_REQUEST"
export const UPDATE_NETWORK_SUCCESS ="UPDATE_NETWORK_SUCCESS"
export const UPDATE_NETWORK_FAIL ="UPDATE_NETWORK_FAIL"


export const GET_NETWORK_REQUEST ="GET_NETWORK_REQUEST"
export const GET_NETWORK_SUCCESS ="GET_NETWORK_SUCCESS"
export const GET_NETWORK_FAIL ="GET_NETWORK_FAIL"


export const NETWORK_DELETED_SUCCESS ="NETWORK_DELETED_SUCCESS"

export const CLEAR_ERRORS ="CLEAR_ERRORS"